site_name: Mis apuntes
site_url: https://ymorgil.github.io/formacion/

theme:
   name: material
   language: es
   # logo: assets/favicon.svg
   palette:
      - scheme: default
        primary: green
        accent: indigo
        toggle:
           icon: material/toggle-switch-off-outline
           name: Modo oscuro
      - scheme: slate
        primary: pink
        accent: green
        toggle:
           icon: material/toggle-switch
           name: Modo claro
nav:
   - Inicio: index.md
   - Inglés:
        - 01 Verbos: ingles/01verbos.md
        - 02 Verbos I: ingles/02verbosi.md
        - 03 Grammar I: ingles/03grammar.md
        - 04 Grammar II: ingles/04grammar2.md
        - 05 Phrasal Verbs: ingles/05phrasal.md
        - 10 Recursos: ingles/10recursos.md
        - 11 Dudas: ingles/11dudas.md
        - 12 Duolingo: ingles/12duo.md
        - 13 Pronunciación: ingles/13pronu.md
        - 20 Audiobooks: ingles/20audiobooks.md
        - 21 Vocabulario: ingles/21vocab.md

plugins:
   - glightbox # Cuando el usuario hace clic en una imagen se abre en una ventana emergente (lightbox)

extra_css:
   - assets/css/extra.css

markdown_extensions:
   - attr_list
   - tables
